name: Build EXE and Upload Artifact

on:
  push:
    branches: [ master ]
  workflow_dispatch:
  schedule:
    - cron:  '0 8 * * 4'

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: powershell

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install pip
      run: |
        python -m ensurepip --upgrade

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller

    - name: Run build script
      run: |
        pyinstaller --onefile Lab678.py

    - name: Upload EXE artifact
      uses: actions/upload-artifact@v3
      with:
        name: Lab678
        path: dist/Lab678.py
